// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2pYo9B9gTIBnOVCaB5HR34k8dvUV4cxU',
    appId: '1:416128129703:web:3038f644f45abbbf5cd982',
    messagingSenderId: '416128129703',
    projectId: 'my-ddfeer-gg-project',
    authDomain: 'my-ddfeer-gg-project.firebaseapp.com',
    storageBucket: 'my-ddfeer-gg-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxw2zc_RnaCMT0xqeTH7C617p8bkPmoXE',
    appId: '1:416128129703:android:c870bc69aad1d3a35cd982',
    messagingSenderId: '416128129703',
    projectId: 'my-ddfeer-gg-project',
    storageBucket: 'my-ddfeer-gg-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTLqmu5-VU0taH-X5CSOdxjx7jUy3xhwM',
    appId: '1:416128129703:ios:e15951ed3320e4f65cd982',
    messagingSenderId: '416128129703',
    projectId: 'my-ddfeer-gg-project',
    storageBucket: 'my-ddfeer-gg-project.firebasestorage.app',
    iosBundleId: 'com.example.aMng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTLqmu5-VU0taH-X5CSOdxjx7jUy3xhwM',
    appId: '1:416128129703:ios:e15951ed3320e4f65cd982',
    messagingSenderId: '416128129703',
    projectId: 'my-ddfeer-gg-project',
    storageBucket: 'my-ddfeer-gg-project.firebasestorage.app',
    iosBundleId: 'com.example.aMng',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2pYo9B9gTIBnOVCaB5HR34k8dvUV4cxU',
    appId: '1:416128129703:web:97c04f5b906fead75cd982',
    messagingSenderId: '416128129703',
    projectId: 'my-ddfeer-gg-project',
    authDomain: 'my-ddfeer-gg-project.firebaseapp.com',
    storageBucket: 'my-ddfeer-gg-project.firebasestorage.app',
  );
}
